CC=pdflatex
CFLAGS=-synctex=1 -interaction=nonstopmode --shell-escape

all: 
	-$(CC) $(CFLAGS) Rapport_ProjetHuffman.tex
	-$(CC) $(CFLAGS) Rapport_ProjetHuffman.tex
	
clean :
	rm -rf *.toc
	rm -rf *.aux
	rm -rf *.log
	rm -rf *.pdf
	rm -rf *.out
	rm -rf *.gz

